#!/bin/sh

clear

echo "=============================="
echo " VPS 初始化脚本"
echo "=============================="
echo ""

# =========================
# SSH 公钥
# =========================

NAT_KEY='ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE23Oz0PWi6phUxz0AylhhKMniWY9FA/WKlmEUpbVwpV Generated By NeoServer'

ROOT_KEY='ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFgQVEPN1MvHxL8WGo2XHaG5w/OGT/OZQD03shzNbuTr Generated By NeoServer'

mkdir -p ~/.ssh
touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys

echo "请选择要写入的 SSH 公钥："
echo "1) nat 公钥"
echo "2) root 公钥"
echo "3) 两个都写入"
echo "4) 跳过"
echo ""

read -p "请输入选项: " keychoice

case $keychoice in
    1)
        echo "$NAT_KEY" >> ~/.ssh/authorized_keys
        ;;
    2)
        echo "$ROOT_KEY" >> ~/.ssh/authorized_keys
        ;;
    3)
        echo "$NAT_KEY" >> ~/.ssh/authorized_keys
        echo "$ROOT_KEY" >> ~/.ssh/authorized_keys
        ;;
    4)
        echo "跳过写入公钥。"
        ;;
    )
        echo "无效选项。"
        ;;
esac

echo ""
echo "正在验证 SSH 公钥是否写入成功..."
echo ""

KEY_OK=0

if grep -q "AAAAC3NzaC1lZDI1NTE5AAAAIE23Oz0PWi6phUxz0AylhhKMniWY9FA/WKlmEUpbVwpV" ~/.ssh/authorized_keys; then
    echo "nat 公钥已成功写入。"
    KEY_OK=1
fi

if grep -q "AAAAC3NzaC1lZDI1NTE5AAAAIFgQVEPN1MvHxL8WGo2XHaG5w/OGT/OZQD03shzNbuTr" ~/.ssh/authorized_keys; then
    echo "root 公钥已成功写入。"
    KEY_OK=1
fi

if [ "$KEY_OK" -eq 0 ]; then
    echo "未检测到有效公钥！"
fi

# =========================
# SSH 密码登录
# =========================

if [ "$KEY_OK" -eq 1 ]; then
    echo ""
    echo "是否关闭 SSH 密码登录？(y/n)"
    read disablepass

    if [ "$disablepass" = "y" ]; then

        sed -i 's/^#?PasswordAuthentication./PasswordAuthentication no/g' /etc/ssh/sshd_config

        sed -i 's/^#?PermitRootLogin.*/PermitRootLogin prohibit-password/g' /etc/ssh/sshd_config

        service sshd restart

        echo "已关闭密码登录，仅允许 SSH 密钥登录。"
    else
        echo "保留密码登录。"
    fi
else
    echo ""
    echo "由于未检测到有效公钥，为防止锁死 VPS，已跳过关闭密码登录。"
fi

# =========================
# 修改 hostname
# =========================

echo ""
echo "是否修改主机名？(y/n)"
read changehost

if [ "$changehost" = "y" ]; then
    echo "请输入新的主机名:"
    read newhost

    hostname "$newhost"
    echo "$newhost" > /etc/hostname

    echo "主机名已修改为: $newhost"
fi

# =========================
# 时区设置
# =========================

echo ""
echo "时区选项："
echo "1) 亚洲/上海"
echo "2) 保持当前"
echo ""

read -p "请选择: " timezonechoice

case $timezonechoice in
    1)
        if [ -f /usr/share/zoneinfo/Asia/Shanghai ]; then
            cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
            echo "Asia/Shanghai" > /etc/timezone
            echo "时区已修改为 Asia/Shanghai"
        else
            echo "系统无时区文件，跳过。"
        fi
        ;;
    2)
        echo "保持当前时区。"
        ;;
esac

# =========================
# WARP
# =========================

echo ""
echo "WARP 网络选项："
echo "1) 保持当前网络"
echo "2) 跳过"
echo ""

read -p "请选择: " warpchoice

case $warpchoice in
    1)
        echo "保持当前网络。"
        ;;
    2)
        echo "跳过 WARP 设置。"
        ;;
esac

# =========================
# Swap
# =========================

echo ""
echo "Swap 选项："
echo "1) 512M"
echo "2) 1G"
echo "3) 2G"
echo "4) 跳过"
echo ""

read -p "请选择: " swapchoice

case $swapchoice in
    1)
        SWAPSIZE=512M
        ;;
    2)
        SWAPSIZE=1G
        ;;
    3)
        SWAPSIZE=2G
        ;;
    4)
        SWAPSIZE=""
        ;;
esac

if [ -n "$SWAPSIZE" ]; then

    if [ ! -f /swapfile ]; then

        fallocate -l $SWAPSIZE /swapfile 2>/dev/null || dd if=/dev/zero of=/swapfile bs=1M count=$(echo $SWAPSIZE | sed 's/G/*1024/' | sed 's/M//g' | bc)

        chmod 600 /swapfile
        mkswap /swapfile

        if swapon /swapfile; then
            echo "/swapfile none swap sw 0 0" >> /etc/fstab
            echo "Swap 创建成功。"
        else
            echo "当前 VPS 不支持 Swap。"
            rm -f /swapfile
        fi
    else
        echo "Swap 已存在。"
    fi
fi

# =========================
# 常用 alias
# =========================

if ! grep -q "alias ll=" ~/.profile 2>/dev/null; then
cat >> ~/.profile << EOF

alias ll='ls -alh'
alias la='ls -A'
alias l='ls -CF'
alias cls='clear'

EOF
fi

# =========================
# 输出机器信息
# =========================

echo ""
echo "=============================="
echo " VPS 初始化完成"
echo "=============================="
echo ""

echo "主机名:"
hostname

echo ""
echo "系统信息:"
uname -a

echo ""
echo "公网 IPv4:"
wget -qO- ipv4.ip.sb 2>/dev/null

echo ""
echo "公网 IPv6:"
wget -qO- ipv6.ip.sb 2>/dev/null

echo ""
echo "SSH 公钥:"
cat ~/.ssh/authorized_keys

echo ""
echo "当前时间:"
date

echo ""
echo "初始化完成。"
