#!/usr/bin/env bash

set -e

GREEN="\033[32m"
RED="\033[31m"
RESET="\033[0m"

clear

echo -e "${GREEN}"
echo "=================================="
echo "         VPS INIT SCRIPT          "
echo "=================================="
echo -e "${RESET}"

# =========================
# Detect OS
# =========================

if [ -f /etc/alpine-release ]; then
    OS="alpine"
elif [ -f /etc/debian_version ]; then
    OS="debian"
else
    echo -e "${RED}Unsupported OS${RESET}"
    exit 1
fi

echo -e "${GREEN}Detected OS:${RESET} $OS"

# =========================
# Update System
# =========================

echo
read -p "Update system packages? (y/n): " update_system

if [ "$update_system" = "y" ]; then

    if [ "$OS" = "alpine" ]; then
        apk update && apk upgrade
        apk add --no-cache bash curl wget sudo tzdata util-linux
    else
        apt update && apt upgrade -y
        apt install -y curl wget sudo tzdata
    fi

    echo -e "${GREEN}System updated.${RESET}"
fi

# =========================
# SSH Public Key
# =========================

echo
echo "SSH Key Options:"
echo "1) nat"
echo "2) root"
echo "3) Custom"
echo "4) Skip"

read -p "Choose: " key_choice

case $key_choice in

    1)
        PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE23Oz0PWi6phUxz0AylhhKMniWY9FA/WKlmEUpbVwpV Generated By NeoServer"
        ;;

    2)
        PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFgQVEPN1MvHxL8WGo2XHaG5w/OGT/OZQD03shzNbuTr Generated By NeoServer"
        ;;

    3)
        echo
        echo "Paste your SSH public key:"
        read -r PUBKEY
        ;;

    *)
        PUBKEY=""
        ;;
esac

if [ -n "$PUBKEY" ]; then

    mkdir -p ~/.ssh
    chmod 700 ~/.ssh

    touch ~/.ssh/authorized_keys
    chmod 600 ~/.ssh/authorized_keys

    if ! grep -qF "$PUBKEY" ~/.ssh/authorized_keys; then
        echo "$PUBKEY" >> ~/.ssh/authorized_keys
    fi

    echo -e "${GREEN}SSH key installed.${RESET}"

    echo
    read -p "Disable password login? (y/n): " disable_pass

    if [ "$disable_pass" = "y" ]; then

        if [ -f /etc/ssh/sshd_config ]; then

            sed -i 's/^#PasswordAuthentication./PasswordAuthentication no/' /etc/ssh/sshd_config
            sed -i 's/^#PermitRootLogin./PermitRootLogin prohibit-password/' /etc/ssh/sshd_config

            if command -v systemctl >/dev/null 2>&1; then
                systemctl restart ssh || systemctl restart sshd || true
            else
                service ssh restart || service sshd restart || true
            fi

            echo -e "${GREEN}Password login disabled.${RESET}"
        fi
    fi
fi

# =========================
# Hostname
# =========================

echo
read -p "Change hostname? (y/n): " change_host

if [ "$change_host" = "y" ]; then

    read -p "New hostname: " NEW_HOSTNAME

    if command -v hostnamectl >/dev/null 2>&1; then
        hostnamectl set-hostname "$NEW_HOSTNAME"
    else
        echo "$NEW_HOSTNAME" > /etc/hostname
        hostname "$NEW_HOSTNAME"
    fi

    echo -e "${GREEN}Hostname changed.${RESET}"
fi

# =========================
# Timezone
# =========================

echo
echo "Timezone Options:"
echo "1) Asia/Shanghai"
echo "2) Keep current"

read -p "Choose: " tz_choice

if [ "$tz_choice" = "1" ]; then

    if [ "$OS" = "alpine" ]; then
        cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo "Asia/Shanghai" > /etc/timezone
    else
        timedatectl set-timezone Asia/Shanghai
    fi

    echo -e "${GREEN}Timezone updated.${RESET}"
fi

# =========================
# WARP Option
# =========================

echo
echo "WARP Options:"
echo "1) Keep current network"
echo "2) Skip"

read -p "Choose: " warp_choice

# Reserved for future WARP support

# =========================
# Swap
# =========================

echo
echo "Swap Options:"
echo "1) 512M"
echo "2) 1G"
echo "3) 2G"
echo "4) Skip"

read -p "Choose: " swap_choice

case $swap_choice in
    1)
        SWAP_MB=512
        ;;
    2)
        SWAP_MB=1024
        ;;
    3)
        SWAP_MB=2048
        ;;
    *)
        SWAP_MB=0
        ;;
esac

if [ "$SWAP_MB" -gt 0 ]; then

    if [ ! -f /swapfile ]; then

        fallocate -l ${SWAP_MB}M /swapfile || 
        dd if=/dev/zero of=/swapfile bs=1M count=$SWAP_MB

        chmod 600 /swapfile

        mkswap /swapfile
        swapon /swapfile

        grep -q "/swapfile" /etc/fstab || 
        echo '/swapfile none swap sw 0 0' >> /etc/fstab

        echo -e "${GREEN}Swap created.${RESET}"
    else
        echo "Swap already exists."
    fi
fi

# =========================
# Common Aliases
# =========================

echo
read -p "Install common aliases? (y/n): " install_alias

if [ "$install_alias" = "y" ]; then

cat >> ~/.bashrc << 'EOF'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias cls='clear'

alias dps='docker ps -a'
alias di='docker images'
alias dc='docker compose'

alias update='apt update && apt upgrade -y || apk update && apk upgrade'

EOF

    echo -e "${GREEN}Aliases installed.${RESET}"
fi

# =========================
# VPS Summary
# =========================

echo

IPV4=$(curl -4 -s ip.sb || echo "N/A")
IPV6=$(curl -6 -s ip.sb || echo "N/A")

HOSTNAME=$(hostname)

if [ -f /etc/timezone ]; then
    TIMEZONE=$(cat /etc/timezone)
else
    TIMEZONE=$(timedatectl | grep "Time zone" | awk '{print $3}')
fi

MEMORY=$(free -h | awk '/Mem:/ {print $2}')
SWAP=$(free -h | awk '/Swap:/ {print $2}')

CPU=$(grep "model name" /proc/cpuinfo | head -1 | cut -d ":" -f2 | xargs)

echo -e "${GREEN}"
echo "=================================="
echo "           VPS SUMMARY           "
echo "=================================="
echo -e "${RESET}"

echo "Hostname : $HOSTNAME"
echo "OS       : $OS"
echo "CPU      : $CPU"
echo "Memory   : $MEMORY"
echo "Swap     : $SWAP"
echo "IPv4     : $IPV4"
echo "IPv6     : $IPV6"
echo "Timezone : $TIMEZONE"

echo
echo -e "${GREEN}Initialization Complete.${RESET}"